---

- name: OpenStack Logging Tools (Kibana, ElasticSearch and FluentD).
  hosts:  
  become: yes
  pre_tasks:

  roles:
  - juliovp01.logging
  - juliovp01.monitoring
  - juliovp01.performance


- hosts: logging_host
  become: yes
  name: Setup logging on servers
  roles:
  - logging
