---
# tasks file for elasticsearch-fluentd-kibana
- hosts: logging_host
  remote_user: root
  vars:
  tasks:
    - include: tasks/prereqs.yml
    - include: tasks/firewall.yml
    - include: tasks/apache.yml
    - include: tasks/elasticsearch.yml
    - include: tasks/kibana.yml
    - include: tasks/fluentd.yml
  handlers:
    - include: handlers/main.yml


- name: Logging clients
  hosts: clients
  remote_user: root
  user: root
  roles:
    - logging
  vars:
    - fluentd_server_fqdn: fluentd-server.fqdn


- hosts: log_client_servers
  vars:
    - fluentd_server_fqdn: fluentd-server.fqdn
  tasks:
    - include: tasks/prereqs.yml
    - include: tasks/clients.yml
  handlers:
    - include: handlers/main.yml