---
# tasks file for server side.
- hosts: performance_host
  remote_user: root
  vars:
  tasks:
    - include: tasks/prereqs.yml
    - include: tasks/firewall.yml
    - include: tasks/apache.yml
    - include: tasks/graphite.yml
  handlers:
    - include: handlers/main.yml

- hosts: localhost
  tasks:
    - include: ../openstack/tasks/main.yml
      when: groups['clients']|length == 0


# tasks for the clients.
- hosts: clients
  remote_user: heat-admin 
  vars:
    - grafana_server_fqdn: 10.12.33.37
  tasks:
    - include: tasks/prereqs.yml
    - include: tasks/clients.yml
  handlers:
    - include: handlers/main.yml
