---
- name: Installing Uchiwa.
  sudo: yes
  yum: name=uchiwa  state=present

- name: Enable Uchiwa.
  sudo: yes
  service: name=uchiwa enabled=yes state=started 

- name: ensure python-selinux is installed on all nodes.
  action: yum name=libselinux-python state=installed  

- name: set SELinux to permissive
  action: selinux policy=targeted state=permissive

- name: Set configuration file for Uchiwa dashboard.
  copy: src=files/uchiwa.json dest=/etc/uchiwa/uchiwa.json
  notify: restart uchiwa
