---
## Client
- name: Installing Fluentd.
  sudo: yes
  yum: name=fluentd  state=present 

- name: Installing Fluentd-Pluging.
  sudo: yes
  yum: name=rubygem-fluent-plugin-add  state=present 

- name: Enable Fluentd.
  sudo: yes
  service: name=fluentd enabled=yes state=started

# Forwarder
- template: src=forwarder.conf.j2 dest=/etc/fluentd/fluent.conf owner=root group=root mode=644
  notify: restart fluentd

- name: Add users to Fluentd Group.
  sudo: yes
  shell: for user in {keystone,nova,neutron,cinder,glance}; do  usermod -a -G $user fluentd; done
  ignore_errors: yes
  notify: restart fluentd

