---
- name: Installing Elasticsearch.
  sudo: yes
  yum: name=elasticsearch  state=present

- name: Enable Elasticsearch.
  sudo: yes
  service: name=elasticsearch enabled=yes state=started  

- name: Copy Configuration file for Fluentd
  copy: src=files/elasticsearch.yml.file dest=/etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch