---
galaxy_info:
  author: Julio Villarreal
  description: Role to install and configure Grafana + Graphite + CollectD on RHEL 7 to do performance monitoring of a  RHEL OSP Installation
  company: Red Hat, Inc.
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
  - development
  - monitoring
  - system
dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.