---
# tasks file for elasticsearch-fluentd-kibana
- hosts: monitoring_host
  remote_user: root
  vars:
  tasks:
    - include: tasks/prereqs.yml
    - include: tasks/firewall.yml
    - include: tasks/sensu.yml
    - include: tasks/uchiwa.yml
  handlers:
    - include: handlers/main.yml

- hosts: localhost
  tasks:
    - include: ../openstack/tasks/main.yml
      when: groups['clients']|length == 0

# tasks for the clients.
- hosts: clients
  remote_user: heat-admin 
  tags: clients
  vars:
    - sensu_server_fqdn: 10.12.33.36
  tasks:
    - include: tasks/prereqs.yml
    - include: tasks/clients.yml
  handlers:
    - include: handlers/main.yml
